# Generated by Django 2.0.6 on 2018-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
