# Generated by Django 2.0.6 on 2018-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photogallery', '0002_auto_20180607_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
