# Generated by Django 2.0.6 on 2018-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photogallery', '0003_auto_20180607_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
